[package]
name = "rustrunner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tiny_http = "0.12"
wasi-common = "15.0.1"
wasmtime = "15.0.1"
wasmtime-wasi = { version = "15.0.1", features = ["sync"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
