[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http = "0.12"
log = "0.4"
env_logger = "0.11"
ureq = { version = "2", default-features = false, features = ["tls"] }
serde_json = "1"
